### PR TITLE
Co2 sensor impl

### PR DESCRIPTION
**Pull request by OZoneSQT**
Updated according to comments

### CODE REVIEW

**Comment by jhviggo** [comment]
The temperature and humidity classes are still in the file changes, please remove them so we do not cause conflicts with Florina.

**Comment by jhviggo** [comment]
Now you just deleted the files completely with the stuff Florina did, I meant you should just remove the changes you had on them :) Do you mind if I change your Pull request to remove florinas changes and squash all of the commits into one?

**Review by jhviggo — APPROVED** [review]
Please check and make sure everything is there before merging 😄

**Comment by OZoneSQT** [comment]
It's there

**Pull request merged**
